domain: zhuty18.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://zhuty18.github.io # the base hostname and protocol for your site, e.g. http://example.com
baseurl: / # place folder name if the site is served in a subfolder
remote_theme: pages-themes/slate@v0.2.0
plugins:
    - jekyll-remote-theme
title: ç‹¡å…”ç™¾çªŸ
description: å…”å­è‰çš„ä¸ªäººä¸»é¡µ

date_format: "%Y. %-m. %-d"
excerpt_word: 300
future: true

redirect_back: /

nav-foot:
    - name: â¬†ï¸
      link: "#main_content"
    - name: ğŸ 
      link: /
    # - name: ğŸ“š
    #   link: /aoom/docs

defaults:
    - scope:
          path: ""
          type: "pages"
      values:
          layout: "custom_default"

ad: purchase
ad_url: https://weibo.com/6193467293/5108192609304587
ddl: 2025-01-03
